import os
from gprbuild_utils import *

def print_inst(lines):
    print lines[0]

    # cp or ln lines to be sorted
    cp=[]
    # remaining lines
    r=[]
    for l in lines[1:]:
        if l[0:3] == 'cp ' or l[0:3] == 'ln ':
            cp = cp + [l]
        else:
            r = r + [l]

    cp.sort()
    for l in cp:
        print l.replace('\\', '/').replace('.dll', '.so').replace('.dylib', '.so')
    for l in r:
        if l[0:49] == '--  This project has been generated by GPRINSTALL':
            print l[0:49]
        else:
            print l.replace('\\', '/')

gprbuild ('hlf.gpr')

gprinstall (['--no-lib-link', '--prefix=/opt', '--dry-run', 'hlf.gpr'],
            output='tmp1.out', verbose=True)
print_inst(open('tmp1.out').readlines())
