import os
from gprbuild_utils import *

gprbuild ('prj/lib1.gpr')

gprinstall (['--prefix='+os.getcwd()+"/inst",
            '--sources-subdir=include/prj/deep',
            '--lib-subdir=xyz',
            '--project-subdir=prj/keep/deep/the/file',
            'prj/lib1.gpr'])

gprinstall (['-f', '--prefix='+os.getcwd()+"/inst",
            '--sources-subdir=include/prj/deep',
            '--lib-subdir=azerty',
            '--project-subdir=prj/keep/deep/the/file',
            'prj/lib1.gpr'])

gprbuild (['-aPinst/prj/keep/deep/the/file', 'main.gpr'])

lines=open('inst/prj/keep/deep/the/file/lib1.gpr', 'r').readlines()

for l in lines:
    if l[0:49] == '--  This project has been generated by GPRINSTALL':
        print l[0:49]
    else:
        print l.replace('\\', '/')

run ("main")

gprinstall (['--prefix='+os.getcwd()+"/inst",
            '--project-subdir=prj/keep/deep/the/file',
            '--uninstall', 'lib1.gpr'])

if os.path.exists("inst"):
    print "ERROR: inst still there"
else:
    print "OK, removed"
