import os, string
from gprbuild_utils import *

found=False

def print_inst(lines):
    # cp or ln lines to be sorted
    cp=[]
    for l in lines[1:]:
        if l[0:3] == 'cp ' or l[0:3] == 'ln ':
            cp = cp + [string.lower(l)]

    cp.sort()
    for l in cp:
        print l.replace('\\', '/').replace('.dylib', '.so')

gprbuild ('prj/lib.gpr')

gprinstall (['-p', '-v', '-m', '--prefix='+os.getcwd()+'/inst', 'prj/lib.gpr'],
            output='tmp.out')
res = open('tmp.out').readlines()
print_inst (res)

gprbuild (['-aPinst/share/gpr', 'main.gpr'])

lines=open('inst/share/gpr/lib.gpr', 'r').readlines()

# Sort the naming spec/body suffix for stable output across platforms

for k in range(0,len(lines)-1):
    if found == False and (lines[k].strip()[0:8] == "for spec" or lines[k].strip()[0:8] == "for body"):
        lines[k:k+4] = sorted(lines[k:k+4])
        found=True

for l in lines:
    if l[0:49] == '--  This project has been generated by GPRINSTALL':
        print l[0:49]
    else:
        print l.replace('\\', '/')

env.add_dll_path ("inst/bin")

run ("main")
